trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.14.0'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
    npm run test
  displayName: 'Build and Test'
  workingDirectory: '$(System.DefaultWorkingDirectory)/frontend'

  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/myFunctionApp.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(75454d79-9582-41ee-b161-972d8629f87c)'
    appType: 'webAppLinux'
    appName: 'dgapp'
    package: '$(Build.ArtifactStagingDirectory)/myFunctionApp.zip'
