trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
  displayName: 'Install Yarn'

- script: |
    yarn install --frozen-lockfile
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Build application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/myFunctionApp.zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(75454d79-9582-41ee-b161-972d8629f87c)'
    appType: 'webAppLinux'
    appName: 'dgapp'
    package: '$(Build.ArtifactStagingDirectory)/myFunctionApp.zip'
  displayName: 'Deploy to Azure Web App'