trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodejsVersion: '14.x'

steps:
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(75454d79-9582-41ee-b161-972d8629f87c)'
    appType: 'functionAppLinux'
    appName: 'dgapp'
    package: '$(System.DefaultWorkingDirectory)/myFunctionApp.zip'
    runtimeStack: 'NODE|14-lts'
  displayName: 'Deploy to Azure Functions'

- task: NodeTool@0
  inputs:
    versionSpec: '$(nodejsVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: true
    archiveFile: '$(System.DefaultWorkingDirectory)/myFunctionApp.zip'
  displayName: 'Create artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/myFunctionApp.zip'
    artifactName: 'myFunctionApp'
    publishLocation: 'pipeline'
  displayName: 'Publish artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(75454d79-9582-41ee-b161-972d8629f87c)'
    appType: 'webAppLinux'
    appName: 'dgapp'
    package: '$(Pipeline.Workspace)/myFunctionApp.zip'
  displayName: 'Deploy to Azure Web App'